name: "Tag & Deploy Action"

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Configure Git
      run: |
        git config --global user.email "veedubusc@gmail.com"
        git config --global user.name "Drew Heavner"

    - name: Build Action
      run: |
        npm ci
        npm run build

    - name: Update v1 Tag
      run: |
        npm prune --production
        git add .
        git commit -m "Pruning Node Modules, Preparing for release"
        git tag -fa v1 -m "Update v1 tag"
        git push origin --force --tags
